# Generated by Django 3.2.8 on 2022-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo_Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primer_Lugar', models.CharField(max_length=50)),
                ('Segundo_Lugar', models.CharField(max_length=50)),
                ('Tercer_Lugar', models.CharField(max_length=50)),
                ('Cuarto_Lugar', models.CharField(max_length=50)),
                ('Quinto_Lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('Sexto_Lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('Septimo_Lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('Octavo_Lugar', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
