# Generated by Django 3.2.8 on 2022-03-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_torneo_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duelista',
            old_name='torneos_jugados',
            new_name='torneos_clasificados',
        ),
    ]
