# Generated by Django 3.2.8 on 2022-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_torneos_jugados_duelista_torneos_clasificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelista',
            name='ptos',
            field=models.IntegerField(),
        ),
    ]
