# Generated by Django 3.2.8 on 2022-03-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carta_ruling'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruling',
            name='nombre',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
