# Generated by Django 3.2.8 on 2022-03-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ruling_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruling',
            name='cartas',
        ),
        migrations.AddField(
            model_name='ruling',
            name='cartas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.carta'),
            preserve_default=False,
        ),
    ]
