# Generated by Django 3.2.8 on 2022-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220325_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruling',
            name='cartas',
        ),
        migrations.AddField(
            model_name='ruling',
            name='cartas',
            field=models.ManyToManyField(to='main.Carta'),
        ),
    ]
