# Generated by Django 3.2.8 on 2022-03-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220325_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruling',
            name='cartas',
        ),
        migrations.DeleteModel(
            name='Carta',
        ),
        migrations.DeleteModel(
            name='Ruling',
        ),
    ]
