# Generated by Django 3.2.8 on 2022-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_carta_ruling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='ruling',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cartas'),
        ),
    ]
