# Generated by Django 3.2.8 on 2022-03-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220331_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruling',
            name='cartas',
        ),
        migrations.DeleteModel(
            name='Carta',
        ),
        migrations.DeleteModel(
            name='Ruling',
        ),
    ]
